version: '2'

services:
  app:
    image: teampass/teampass:latest
    ports:
    - 80:80
    volumes:
    - teampass_data:/var/www/html
  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=teampass
    volumes:
    - teampass_data:/var/lib/mysql

volumes:
  teampass_data: